services:
  shopify:
    build: .
    volumes:
      - .:/app
      - shopify_auth:/root/.local/share/shopify
    ports:
      - "9292:9292"
      - "9393:9393"
    env_file: .env
    working_dir: /app
    command: shopify theme dev --store sophior-keuken.myshopify.com --host 0.0.0.0

volumes:
  shopify_auth:
